"""empty message

Revision ID: b2a3fd640eb2
Revises: ac2388033e1e
Create Date: 2021-11-19 15:48:20.614104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a3fd640eb2'
down_revision = 'ac2388033e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasien', sa.Column('nama_depan', sa.String(length=50), nullable=True))
    op.add_column('pasien', sa.Column('nama_belakang', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pasien', 'nama_belakang')
    op.drop_column('pasien', 'nama_depan')
    # ### end Alembic commands ###
